name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. (Optional) Run tests
      # - name: Run tests
      #   run: npm test

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t node-hello .
